const {chromium}=require('playwright');
const fs=require('node:fs'),http=require('node:http'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..');
(async()=>{
  const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end(fs.readFileSync(path.join(root,'home-runtime/live-app.html')))});
  await new Promise(r=>server.listen(8776,'127.0.0.1',r));
  const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_PATH||'/usr/bin/google-chrome',args:['--no-sandbox']});
  try{
    const context=await browser.newContext({viewport:{width:393,height:851},isMobile:true,hasTouch:true,timezoneId:'Europe/London'});
    await context.route('https://**/*',r=>r.abort());
    await context.addInitScript(()=>{
      const task={id:'gt:L:a',googleId:'a',googleListId:'L',source:'google-tasks',title:'Read the seminar brief',area:'Tasks',note:'Link to reading',details:{personalNote:'Link to reading'}};
      localStorage.setItem('native:todoState',JSON.stringify({active:[task],archive:[]}));
      window.__ops=[];window.__legacySync=0;window.__offline=false;window.__connected=true;window.__remote=[task];window.__events=[];
      window.__snapshot=()=>({connected:true,open:window.__remote.filter(x=>!x.done),completed:window.__remote.filter(x=>x.done),pendingTaskIds:window.__offline?window.__ops.map(x=>x.localId):[],lists:[{id:'L',title:'Tasks'},{id:'S',title:'Study'}],selectedListId:window.__list||'L',syncedAt:Date.now()});
      window.Native={loadState:k=>localStorage.getItem('native:'+k)||'',saveState:(k,v)=>localStorage.setItem('native:'+k,v),acceptRemoteTodoState:v=>localStorage.setItem('native:todoState',v),liveRuntimeStatus:()=>JSON.stringify({nativeVersion:18,version:'18.google-test'}),markRuntimeHealthy:()=>{},checkLiveUpdate:()=>{},applyLiveUpdate:()=>{},hasNotionConnection:()=>true,requestNotionSync:()=>window.__legacySync++,hasCalendarPermission:()=>true,getCalendarEvents:()=>JSON.stringify(window.__calendar||[]),openUrl:()=>{},openCalendarEvent:()=>{}};
      window.AdaptiveNative={logActivity:s=>window.__events.push(JSON.parse(s)),queuePrivateActivity:()=>true,reviewSentence:()=>{},checkDeviceCommands:()=>{},flushPrivateSync:()=>{}};
      window.GoogleNative={isConnected:()=>window.__connected,status:()=>JSON.stringify(window.__snapshot()),connect:()=>window.__connected=true,sync:()=>{if(!window.__offline)setTimeout(()=>window.onGoogleSnapshot(window.__snapshot()),0)},selectList:id=>{window.__list=id;window.onGoogleSnapshot(window.__snapshot())},enqueue:s=>{const op=JSON.parse(s);window.__ops.push(op);if(!window.__offline){let t=window.__remote.find(x=>x.id===op.localId);if(!t){t={id:op.localId,googleId:'remote-'+op.localId,googleListId:op.listId,source:'google-tasks',area:'Tasks',details:{}};window.__remote.push(t)}if('title'in op.fields)t.title=op.fields.title;if('notes'in op.fields){t.note=op.fields.notes;t.details.personalNote=op.fields.notes}if('status'in op.fields){t.done=op.fields.status==='completed';if(t.done)t.completedAt=Date.now();else delete t.completedAt}if('due'in op.fields)t.due=op.fields.due;}return true}};
    });
    const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto('http://127.0.0.1:8776');await page.waitForFunction(()=>window.VBrainAdaptation&&window.VBrainTube);
    await page.evaluate(()=>showScreen('todos'));assert.equal(await page.locator('#syncButton').textContent(),'Sync Google');
    assert.equal(await page.locator('#v31GoogleList option').count(),2);
    await page.locator('#v31GoogleList').selectOption('S');
    await page.locator('#newTodo').fill('Prepare the customer interview');await page.evaluate(()=>addTodo());
    assert.ok(await page.evaluate(()=>window.__ops.some(x=>x.fields.title==='Prepare the customer interview'&&x.listId==='S')),'V-Brain creations write to the chosen Google list');
    await page.evaluate(()=>{window.onGoogleSnapshot(window.__snapshot());completeTodo('gt:L:a')});
    assert.ok(await page.evaluate(()=>window.__ops.some(x=>x.localId==='gt:L:a'&&x.fields.status==='completed')),'completion writes to Google');
    await page.evaluate(()=>{window.onGoogleSnapshot(window.__snapshot());restoreTodo('gt:L:a')});
    assert.ok(await page.evaluate(()=>window.__ops.some(x=>x.localId==='gt:L:a'&&x.fields.status==='needsAction')),'restoration writes to Google');
    await page.evaluate(()=>{window.onGoogleSnapshot(window.__snapshot());openTodoDetail('gt:L:a')});
    await page.locator('#detailPersonalNote').fill('Ask about the most recent real purchase.');await page.locator('.v31Due input').fill('2026-10-12');await page.locator('.v31Due input').dispatchEvent('change');await page.locator('#detailPersonalNote').blur();
    assert.ok(await page.evaluate(()=>window.__ops.some(x=>x.fields.notes==='Ask about the most recent real purchase.')),'edited notes reach Google');
    assert.ok(await page.evaluate(()=>window.__ops.some(x=>x.fields.due==='2026-10-12T00:00:00.000Z')),'due dates reach Google');
    await page.evaluate(()=>{showScreen('todos');window.__remote=window.__remote.map(x=>x.id==='gt:L:a'?{...x,title:'Google changed this title'}:x);window.onGoogleSnapshot(window.__snapshot())});
    assert.ok((await page.locator('#todoList').textContent()).includes('Google changed this title'),'Google edits replace the cached view');
    await page.evaluate(()=>{window.__remote=window.__remote.filter(x=>x.id!=='gt:L:a');window.onGoogleSnapshot(window.__snapshot())});
    assert.ok(!(await page.locator('#todoList').textContent()).includes('Google changed this title'),'Google deletions stay deleted');
    assert.ok(await page.evaluate(()=>JSON.parse(Native.loadState('vbrainGoogleRemovedV31')).some(x=>x.id==='gt:L:a')),'removed task notes remain recoverable');
    await page.locator('#v31GoogleRecovery summary').click();assert.ok((await page.locator('#v31GoogleRecovery').textContent()).includes('most recent real purchase'),'saved notes can be reviewed inside the app');
    await page.locator('#v31GoogleRecovery button').click();assert.ok(await page.evaluate(()=>window.__ops.some(x=>x.fields.title==='Google changed this title'&&!x.googleId&&x.fields.status==='needsAction')),'recovery creates a new task only after an explicit user action');
    await page.evaluate(()=>{window.__offline=true});await page.locator('#newTodo').fill('Offline commitment');await page.evaluate(()=>addTodo());
    assert.ok((await page.locator('#todoList').textContent()).includes('Offline commitment'));
    assert.ok(await page.evaluate(()=>JSON.parse(Native.loadState('todoState')).active.some(x=>x.title==='Offline commitment')),'offline work persists before a network acknowledgement');
    await page.evaluate(()=>{window.__calendar=[{id:'google:L:event',title:'Changed on Google Calendar',start:Date.now(),end:Date.now()+3600000,allDay:false}];showScreen('calendar');onGoogleCalendarChanged()});
    assert.ok((await page.locator('#calendarList').textContent()).includes('Changed on Google Calendar'));
    await page.evaluate(()=>{window.__calendar=[];onGoogleCalendarChanged()});assert.ok((await page.locator('#calendarList').textContent()).includes('Nothing scheduled'),'calendar cancellation removes the event');
    await page.evaluate(()=>showScreen('tube'));const first=await page.evaluate(()=>tubeState.activeIds[0]);
    await page.evaluate(()=>openCard(tubeState.activeIds[0],0));await page.locator('#answer').fill('I would test this idea with a real customer before scaling it.');
    await page.locator('#reader .option').first().click();await page.locator('#submit').click();await page.locator('#next').click();
    assert.ok(!(await page.evaluate(()=>tubeState.activeIds)).includes(first),'a completion replaces the card with a fresh one');
    const after=await page.evaluate(()=>tubeState.activeIds[0]);await page.evaluate(()=>{openCard(tubeState.activeIds[0],0)});await page.locator('#answer').fill('A draft that must survive the next update');await page.evaluate(()=>closeReader());
    await page.evaluate(()=>{const key='vbrainTubeScheduleV31',state=JSON.parse(Native.loadState(key));for(const id of tubeState.activeIds)state.seen[id]=Date.now()-3*86400000;Native.saveState(key,JSON.stringify(state));VBrainAdaptation.evaluate(true);renderDeck()});
    assert.ok((await page.evaluate(()=>tubeState.activeIds)).includes(after),'stale refresh protects draft answers');
    const model=await page.evaluate(()=>VBrain.model(true));assert.ok(model.nodes.some(x=>x.id.startsWith('knowledge:')),'learning grows real knowledge branches');
    assert.ok(await page.evaluate(()=>{const last=tubeState.completed.at(-1);last.semanticReview={assessmentValid:false,depth:0};return VBrain.model(true).nodes.filter(x=>x.id.startsWith('knowledge:')).every(x=>x.active===false)}),'an invalid assessment cannot become low-ability evidence');
    await page.evaluate(()=>{delete tubeState.completed.at(-1).semanticReview;VBrain.branch(['learning'],{id:'retained-test',label:'Retain this branch'})});await page.reload();await page.waitForFunction(()=>window.VBrain);
    assert.ok((await page.evaluate(()=>VBrain.model(true))).nodes.some(x=>x.id==='retained-test'),'brain branches survive a new release boot');
    assert.equal(await page.evaluate(()=>window.__legacySync),0,'Google data never enters the competing legacy task reader');
    assert.ok(await page.evaluate(()=>VBrainAdaptation.status().baseline&&VBrainAdaptation.status().journal.length),'accepted guidance and its reasons persist');
    assert.deepEqual(errors,[]);await page.screenshot({path:path.join(root,'google-home-screen-test.png'),fullPage:true});
    console.log('PASS: Google Tasks creation/completion/restore/notes/dates/list selection; remote edits/deletes; offline persistence; live calendar; fresh cards/draft protection; evolving persistent brain.');
  }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exit(1)});
