import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { createMcpHandler, McpServer } from 'npm:@modelcontextprotocol/server@2.1.0'
import { withOAuthProtectedResource, withSupabase } from 'npm:@supabase/server@1.8.0'
import { z } from 'npm:zod@4.6.5'

function result(text:string,data:Record<string,unknown>){return {content:[{type:'text' as const,text}],structuredContent:data}}

Deno.serve(withOAuthProtectedResource(withSupabase({auth:'user'},async(req,{supabase})=>{
 const handler=createMcpHandler(()=>{
  const server=new McpServer({name:'veqrya-personal-os',version:'0.3.0'},{instructions:'Veqrya stores only the signed-in user’s tasks and learning progress. Read current Veqrya data before planning. Only make changes the user clearly requests.'})

  server.registerTool('get_home_snapshot',{title:'Get Veqrya snapshot',description:'Read the signed-in user’s open and recently completed Veqrya tasks, active learning cards and profile settings.',inputSchema:{task_limit:z.number().int().min(1).max(100).default(50),learning_limit:z.number().int().min(1).max(50).default(10)},annotations:{readOnlyHint:true,openWorldHint:false,destructiveHint:false}},async({task_limit,learning_limit})=>{
   const [a,b,c,d]=await Promise.all([
    supabase.from('home_tasks').select('id,title,notes,status,due_at,area,priority,created_at,updated_at').eq('status','open').order('due_at',{ascending:true,nullsFirst:false}).limit(task_limit),
    supabase.from('home_tasks').select('id,title,notes,status,due_at,area,priority,created_at,updated_at').eq('status','done').order('updated_at',{ascending:false}).limit(20),
    supabase.from('home_learning_cards').select('id,title,topic,content,status,created_at,updated_at').eq('status','active').order('updated_at',{ascending:false}).limit(learning_limit),
    supabase.from('home_profiles').select('display_name,timezone,settings').maybeSingle()]);
   for(const x of [a,b,c,d])if(x.error)throw new Error(x.error.message);const data={open_tasks:a.data??[],completed_tasks:b.data??[],learning_cards:c.data??[],profile:d.data??null};return result('Veqrya snapshot loaded.',data)
  })

  server.registerTool('list_tasks',{title:'List Veqrya tasks',description:'List tasks stored in Veqrya for the signed-in user.',inputSchema:{status:z.enum(['open','done','archived','all']).default('open'),limit:z.number().int().min(1).max(100).default(50)},annotations:{readOnlyHint:true,openWorldHint:false,destructiveHint:false}},async({status,limit})=>{let q=supabase.from('home_tasks').select('id,title,notes,status,due_at,area,priority,created_at,updated_at').order('due_at',{ascending:true,nullsFirst:false}).limit(limit);if(status!=='all')q=q.eq('status',status);const {data,error}=await q;if(error)throw new Error(error.message);return result('Veqrya tasks loaded.',{tasks:data??[]})})

  server.registerTool('create_task',{title:'Create Veqrya task',description:'Create one Veqrya task. Do not invent a due time.',inputSchema:{title:z.string().trim().min(1).max(200),notes:z.string().max(4000).default(''),due_at:z.string().datetime({offset:true}).nullable().default(null),area:z.string().trim().min(1).max(80).default('Personal'),priority:z.number().int().min(0).max(3).default(1)},annotations:{readOnlyHint:false,openWorldHint:false,destructiveHint:false}},async(v)=>{const {data,error}=await supabase.from('home_tasks').insert(v).select('id,title,notes,status,due_at,area,priority,created_at,updated_at').single();if(error)throw new Error(error.message);return result('Veqrya task created.',{task:data})})

  server.registerTool('update_task',{title:'Update Veqrya task',description:'Update an existing Veqrya task without silently marking it complete.',inputSchema:{id:z.string().uuid(),title:z.string().trim().min(1).max(200).optional(),notes:z.string().max(4000).optional(),due_at:z.string().datetime({offset:true}).nullable().optional(),area:z.string().trim().min(1).max(80).optional(),priority:z.number().int().min(0).max(3).optional(),status:z.enum(['open','done','archived']).optional()},annotations:{readOnlyHint:false,openWorldHint:false,destructiveHint:false}},async({id,...changes})=>{const patch=Object.fromEntries(Object.entries(changes).filter(([,v])=>v!==undefined));if(!Object.keys(patch).length)throw new Error('No changes provided.');const {data,error}=await supabase.from('home_tasks').update(patch).eq('id',id).select('id,title,notes,status,due_at,area,priority,created_at,updated_at').maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error('Task not found.');return result('Veqrya task updated.',{task:data})})

  server.registerTool('complete_task',{title:'Complete Veqrya task',description:'Mark one Veqrya task done only after an explicit user request.',inputSchema:{id:z.string().uuid()},annotations:{readOnlyHint:false,openWorldHint:false,destructiveHint:false}},async({id})=>{const {data,error}=await supabase.from('home_tasks').update({status:'done'}).eq('id',id).select('id,title,notes,status,due_at,area,priority,created_at,updated_at').maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error('Task not found.');return result('Veqrya task completed.',{task:data})})

  server.registerTool('list_learning_cards',{title:'List Veqrya learning cards',description:'List the signed-in user’s Veqrya learning cards for Tube Learning and recall practice.',inputSchema:{status:z.enum(['active','completed','archived','all']).default('active'),limit:z.number().int().min(1).max(50).default(20)},annotations:{readOnlyHint:true,openWorldHint:false,destructiveHint:false}},async({status,limit})=>{let q=supabase.from('home_learning_cards').select('id,title,topic,content,status,created_at,updated_at').order('updated_at',{ascending:false}).limit(limit);if(status!=='all')q=q.eq('status',status);const {data,error}=await q;if(error)throw new Error(error.message);return result('Veqrya learning cards loaded.',{cards:data??[]})})

  server.registerTool('save_learning_card',{title:'Save Veqrya learning card',description:'Save one concise learning card to Veqrya.',inputSchema:{title:z.string().trim().min(1).max(220),topic:z.string().trim().max(120).default(''),content:z.record(z.string(),z.unknown()).default({})},annotations:{readOnlyHint:false,openWorldHint:false,destructiveHint:false}},async(v)=>{const {data,error}=await supabase.from('home_learning_cards').insert(v).select('id,title,topic,content,status,created_at,updated_at').single();if(error)throw new Error(error.message);return result('Veqrya learning card saved.',{card:data})})

  server.registerTool('save_learning_attempt',{title:'Save Veqrya learning attempt',description:'Store a meaningful recall or application attempt and feedback in Veqrya.',inputSchema:{card_id:z.string().uuid().nullable().default(null),reflection:z.string().trim().min(1).max(4000),feedback:z.record(z.string(),z.unknown()).default({}),overall_score:z.number().int().min(0).max(100).nullable().default(null)},annotations:{readOnlyHint:false,openWorldHint:false,destructiveHint:false}},async(v)=>{const {data,error}=await supabase.from('home_learning_attempts').insert(v).select('id,card_id,reflection,feedback,overall_score,created_at').single();if(error)throw new Error(error.message);return result('Veqrya learning attempt saved.',{attempt:data})})

  server.registerTool('export_my_home_data',{title:'Export my Veqrya data',description:'Read all Veqrya application data belonging to the signed-in user.',inputSchema:{},annotations:{readOnlyHint:true,openWorldHint:false,destructiveHint:false}},async()=>{const [p,t,c,a,h]=await Promise.all([supabase.from('home_profiles').select('*').maybeSingle(),supabase.from('home_tasks').select('*').order('created_at',{ascending:true}),supabase.from('home_learning_cards').select('*').order('created_at',{ascending:true}),supabase.from('home_learning_attempts').select('*').order('created_at',{ascending:true}),supabase.from('home_activity').select('*').order('created_at',{ascending:true})]);for(const x of [p,t,c,a,h])if(x.error)throw new Error(x.error.message);return result('Veqrya data export loaded.',{profile:p.data??null,tasks:t.data??[],learning_cards:c.data??[],learning_attempts:a.data??[],activity:h.data??[]})})

  return server
 });return handler.fetch(req)
})))
